### ISSUE TITLE
Suggestion: Define ESLint library type boundary constraints

### ISSUE THREAD

**Issue by labeled** [trungvose/angular-spotify#46]
While this does use NX it does not seem to define the boundary constraints between library types. Many ui libraries are depending on data-access libraries and are outside of the scope nx suggests in their documentation that can be found [here](https://nx.dev/previous/angular/structure/library-types).
Updating the "depConstraints" to match the suggested dependency constraints will cause eslint to fail.
Dependency Constraints
Feature Library -> can depend on any type of library.
UI Library -> can only depend on other ui or util libraries.
Data-access library -> can only depend on data-access and util libraries.
Utility library -> can only depend on utility libraries.

**Comment by trungk18** [comment]
@labeled Thank you so much for the suggestion. I am aware of this, and as mentioned on the README, this is my first Nx project, so I want to get something out quickly. That's why I took some shortcuts to reuse the UI component in the same places and plug them directly into the data access.

That said, I would come in a few weeks. If you feel like you want to create a PR in the meantime, feel free, and thanks again :)

**Comment by nartc** [comment]
The project doesn't have ESLint Boundary setup but most, if not all, libs already have tags defined so applying the boundary should be fairly straight-forward

**Comment by leonlafa** [comment]
Please review my PR https://github.com/trungk18/angular-spotify/pull/77

**Comment by trungk18** [comment]
Thanks @leonlafa, I am looking into it 😁
